#ifndef USE_KERNEL_H
#define USE_KERNEL_H

#include "mininn/graph/register_helper.h"

// when you use any kernel, you should include this file
USE_KERNEL(ADD);
USE_KERNEL(CONV);
USE_KERNEL(CLIP);
USE_KERNEL(SHAPE);
USE_KERNEL(GATHER);
USE_KERNEL(UNSQUEEZE);
USE_KERNEL(CONCAT);
USE_KERNEL(GLOBALAVERAGEPOOL);
USE_KERNEL(RESHAPE);
USE_KERNEL(GEMM);
USE_KERNEL(CONSTANT);

#endif  // USE_KERNEL_H