# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mininn_fbs

class Op(object):
    ADD = 0
    CONV = 1
    CLIP = 2
    SHAPE = 3
    GATHER = 4
    UNSQUEEZE = 5
    CONCAT = 6
    GLOBALAVERAGEPOOL = 7
    RESHAPE = 8
    GEMM = 9
    CONSTANT = 10
